language: cpp
compiler:
  - gcc
  - clang
before_script:
  - mkdir ../build
  - cd ../build
script:
  - cmake ../mp-lab2-matrix
  - make -j
  - cd ./bin/
  - ./test_set --gtest_list_tests
notifications:
  email: false
